In [1]:
lst = [1,2, 3]
lst2 = [4,5, 6]

In [2]:
lst + lst2

[1, 2, 3, 4, 5, 6]

In [3]:
lst + 1

TypeError: can only concatenate list (not "int") to list

In [5]:
import numpy as np
numbers = np.arange(0, 1000, 1)

In [6]:
numbers

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [7]:
numbers[100:200]

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151,
       152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164,
       165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177,
       178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190,
       191, 192, 193, 194, 195, 196, 197, 198, 199])

In [10]:
numbers[-100:]

array([900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912,
       913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925,
       926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938,
       939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951,
       952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964,
       965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977,
       978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990,
       991, 992, 993, 994, 995, 996, 997, 998, 999])

In [12]:
numbers[100:200:3]

array([100, 103, 106, 109, 112, 115, 118, 121, 124, 127, 130, 133, 136,
       139, 142, 145, 148, 151, 154, 157, 160, 163, 166, 169, 172, 175,
       178, 181, 184, 187, 190, 193, 196, 199])

In [14]:
!pip install -r requirements-dev.txt

  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/9b/35/74442388c6cf008882d4d4bdfc4109be87e9b8b7ccd097ad1e7f006e2e95/pandas-2.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata
  Using cached pandas-2.3.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (91 kB)
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/81/c4/34e93fe5f5429d7570ec1fa436f1986fb1f00c3e0f43a589fe2bbcd22c3f/pytz-2025.2-py2.py3-none-any.whl.metadata
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/c7/b0/003792df09decd6849a5e39c28b513c06e84436a54440380862b5aeff25d/tzdata-2025.3-py2.py3-none-any.whl.metadata
Using cached pandas-2.3.3-cp311-cp311-macosx_11_0_arm64.whl (10.8 MB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 348.5/348.5 kB 3.9 MB/s eta 0:00:003.8 MB/s eta 0:00:01



In [ ]:
# Pandas Series
import pandas as pd

s = pd.Series([1,2,3,4,5 , 6], index=['a', 'b', 'c', 'd', 'e', 0])
s


a    1
b    2
c    3
d    4
e    5
0    6
dtype: int64

In [18]:
print(s.loc["d"])

4


In [19]:
print(s.iloc[3])

4


In [22]:
s["d"]

np.int64(4)

In [27]:
s[4]

KeyError: 4

In [24]:
s[0]

np.int64(6)

In [25]:
numbers = np.arange(0, 6, 1)
numbers

array([0, 1, 2, 3, 4, 5])

In [28]:
s = pd.Series([1,2,3,4,5 , 6])
s

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [20]:
import pandas as pd

data = {
    "Make": ["Honda", "BMW", "Honda", "Toyota", "Nissan"],
    "Colour": ["White", "Blue", "White", "White", "Blue"],
    "Odometer (KM)": [35431.0, 192714.0, 84714.0, 154365.0, 181577.0],
    "Doors": [4.0, 5.0, 4.0, 4.0, 3.0],
    "Price ": [15323.0, 19943.0, 28343.0, 13434.0, 14043.0]
}

df = pd.DataFrame(data)
df


Make Colour  Odometer (KM)  Doors   Price 
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [21]:
df.index = df["Make"]

In [22]:
df

Make Colour  Odometer (KM)  Doors   Price 
Make                                                
Honda    Honda  White        35431.0    4.0  15323.0
BMW        BMW   Blue       192714.0    5.0  19943.0
Honda    Honda  White        84714.0    4.0  28343.0
Toyota  Toyota  White       154365.0    4.0  13434.0
Nissan  Nissan   Blue       181577.0    3.0  14043.0

In [23]:
df["Price "]

Make
Honda     15323.0
BMW       19943.0
Honda     28343.0
Toyota    13434.0
Nissan    14043.0
Name: Price , dtype: float64

In [24]:
df.Price 

AttributeError: 'DataFrame' object has no attribute 'Price'

In [16]:
df.columns.str.strip()

Index(['Make', 'Colour', 'Odometer (KM)', 'Doors', 'Price'], dtype='object')

In [25]:
df.columns = df.columns.str.strip()

In [26]:
df

Make Colour  Odometer (KM)  Doors    Price
Make                                                
Honda    Honda  White        35431.0    4.0  15323.0
BMW        BMW   Blue       192714.0    5.0  19943.0
Honda    Honda  White        84714.0    4.0  28343.0
Toyota  Toyota  White       154365.0    4.0  13434.0
Nissan  Nissan   Blue       181577.0    3.0  14043.0

In [27]:
df.Price

Make
Honda     15323.0
BMW       19943.0
Honda     28343.0
Toyota    13434.0
Nissan    14043.0
Name: Price, dtype: float64

In [30]:
df.Doors > 4

Make
Honda     False
BMW        True
Honda     False
Toyota    False
Nissan    False
Name: Doors, dtype: bool

In [29]:
df[df.Doors > 4]

Make Colour  Odometer (KM)  Doors    Price
Make                                           
BMW   BMW   Blue       192714.0    5.0  19943.0

In [32]:
df

Make Colour  Odometer (KM)  Doors    Price
Make                                                
Honda    Honda  White        35431.0    4.0  15323.0
BMW        BMW   Blue       192714.0    5.0  19943.0
Honda    Honda  White        84714.0    4.0  28343.0
Toyota  Toyota  White       154365.0    4.0  13434.0
Nissan  Nissan   Blue       181577.0    3.0  14043.0

In [31]:
df[1:4]

Make Colour  Odometer (KM)  Doors    Price
Make                                                
BMW        BMW   Blue       192714.0    5.0  19943.0
Honda    Honda  White        84714.0    4.0  28343.0
Toyota  Toyota  White       154365.0    4.0  13434.0

In [33]:
df.iloc[1:4, :3]

Make Colour  Odometer (KM)
Make                                
BMW        BMW   Blue       192714.0
Honda    Honda  White        84714.0
Toyota  Toyota  White       154365.0

In [35]:
df.iloc[1:4]

Make Colour  Odometer (KM)  Doors    Price
Make                                                
BMW        BMW   Blue       192714.0    5.0  19943.0
Honda    Honda  White        84714.0    4.0  28343.0
Toyota  Toyota  White       154365.0    4.0  13434.0

In [34]:
df[1:4, :3]

InvalidIndexError: (slice(1, 4, None), slice(None, 3, None))

In [38]:
df[["Make", "Price"]]

Make    Price
Make                   
Honda    Honda  15323.0
BMW        BMW  19943.0
Honda    Honda  28343.0
Toyota  Toyota  13434.0
Nissan  Nissan  14043.0

In [41]:
df.loc[["Honda", 1], ["Price", "Make"]]

KeyError: '[1] not in index'

In [42]:
import pandas as pd

data = {
    "Company": ["GOOG", "GOOG", "MSFT", "MSFT", "FB", "FB"],
    "Person": ["Sam", "Charlie", "Amy", "Vanessa", "Carl", "Sarah"],
    "Sales": [200, 120, 340, 124, 243, 350]
}

df = pd.DataFrame(data)
print(df)


  Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350


In [45]:
df[["Company", "Sales"]].groupby("Company").mean()

Sales
Company       
FB       296.5
GOOG     160.0
MSFT     232.0